version: '3.7'
services:
    file-serve-db:
        image: postgres:alpine
        container_name: file_serve-dev-database
        environment:
            - POSTGRES_PASSWORD=mysecretpassword
            - PGDATA=/var/lib/postgresql/data/pgdata
        volumes:
            - './data/db:/var/lib/postgresql/data'
        ports:
            - "5433:5432"
        restart: always

    mongo:
        image: mongo
        restart: always
        environment:
            MONGO_INITDB_ROOT_USERNAME: root
            MONGO_INITDB_ROOT_PASSWORD: mysecretpassword
        ports:
            - "27017:27017"
