version: '3.7'
services:
    file-serve-db:
        container_name: file-serve-db
        image: mongo
        restart: always
        environment:
            MONGO_INITDB_ROOT_USERNAME: root
            MONGO_INITDB_ROOT_PASSWORD: mysecretpassword
        volumes:
            - ./data:/data/db
        ports:
            - "6002:27017"
