version: '3.7'
services:
    file-serve-db:
        container_name: file-serve-db
        image: mongo
        restart: always
        environment:
            MONGO_INITDB_ROOT_USERNAME: root
            MONGO_INITDB_ROOT_PASSWORD: mysecretpassword
        volumes:
            - ./data:/data/db
        ports:
            - "6002:27017"

    file-serve:
        container_name: file-serve-app
        image: file-serve:latest
        restart: always
        build:
            context: ../..
            dockerfile: deploy/build/dockerfile
        ports:
            - "4003:4003"
        environment:
            AUTHENTICATION_SERVER_URI: "http://host.docker.internal/authentication/"
            DB_HOST: host.docker.internal
